import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <div className="absolute w-full min-h-96 bg-black" />
        <div className="absolute w-full min-h-96 bg-[url('/background.png')] opacity-40" />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
